from relational_stream.flow import Flow as Flow
from typing import Type, TypeVar

T = TypeVar('T')
F = TypeVar('F', bound=Type[Flow])

class RelationalStream:
    flow_types: list[Type[Flow[T]]]
    def __init__(self, flow_types: list[Type[Flow[T]]]) -> None: ...
    def ingest(self, event: T): ...
    def incomplete_flows(self, flow_type: F) -> list[F]: ...
    def completed_flows(self, flow_type: F) -> list[F]: ...
